version: "3.9"

services:

  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=holidays
      - POSTGRES_USER=holidays
      - POSTGRES_PASSWORD=payAlot

  selenium-1:
    build:
      context: .
      dockerfile: ./selenium/Dockerfile
    ports:
      - "4444:4444"
    shm_size: '2gb'

  selenium-2:
    build:
      context: .
      dockerfile: ./selenium/Dockerfile
    ports:
      - "4445:4444"
    shm_size: '2gb'

  rabbit:
    build:
      context: .
      dockerfile: ./rabbitmq/Dockerfile
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=payAlot

  collecting-app-1:
    build:
      context: ./..
      dockerfile: ./infrastructure/collecting-app/Dockerfile
    depends_on:
      - postgres
      - selenium-1
      - rabbit
    environment:
      - OffersDataSource__Provider=Rainbow
      - OffersDataSource__CollectingTimeoutSeconds=60
      - Selenium__RemoteWebDriverUrl=http://selenium-1:4444/wd/hub

  collecting-app-2:
    build:
      context: ./..
      dockerfile: ./infrastructure/collecting-app/Dockerfile
    depends_on:
      - postgres
      - selenium-2
      - rabbit
      - collecting-app-1
    environment:
      - OffersDataSource__Provider=Tui
      - OffersDataSource__CollectingTimeoutSeconds=180
      - Selenium__RemoteWebDriverUrl=http://selenium-2:4444/wd/hub

volumes:
  pgdata: { }
