version: "3.9"

services:

  postgres:
    build:
      context: ./postgres/
      dockerfile: ./Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=holidays
      - POSTGRES_USER=holidays
      - POSTGRES_PASSWORD=payAlot

  selenium-1:
    build:
      context: ./selenium/
      dockerfile: ./Dockerfile
    ports:
      - "4444:4444"
    shm_size: '2gb'

  selenium-2:
    build:
      context: ./selenium/
      dockerfile: ./Dockerfile
    ports:
      - "4445:4444"
    shm_size: '2gb'

  selenium-3:
    build:
      context: ./selenium/
      dockerfile: ./Dockerfile
    ports:
      - "4446:4444"
    shm_size: '2gb'

  rabbit:
    build:
      context: ./rabbitmq/
      dockerfile: ./Dockerfile
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=payAlot

  collecting-app-1:
    build:
      context: ./../src/
      dockerfile: ./Holidays.CollectingApp/Dockerfile
    depends_on:
      - postgres
      - selenium-1
      - rabbit
    environment:
      - ENVIRONMENT=Docker
      - OffersDataSource__Provider=Rainbow
      - OffersDataSource__CollectingTimeoutSeconds=60
      - Postgres__ConnectionString=Server=postgres;Port=5432;Database=holidays;User Id=holidays;Password=payAlot;
      - RabbitMq__HostName=rabbit
      - RabbitMq__Port=5672
      - RabbitMq__VirtualHost=production
      - RabbitMq__UserName=holidays
      - RabbitMq__Password=payAlot
      - Selenium__RemoteWebDriverUrl=http://selenium-1:4444/wd/hub

  collecting-app-2:
    build:
      context: ./../src/
      dockerfile: ./Holidays.CollectingApp/Dockerfile
    depends_on:
      - postgres
      - selenium-2
      - rabbit
      - collecting-app-1
    environment:
      - ENVIRONMENT=Docker
      - OffersDataSource__Provider=Tui
      - OffersDataSource__CollectingTimeoutSeconds=180
      - Postgres__ConnectionString=Server=postgres;Port=5432;Database=holidays;User Id=holidays;Password=payAlot;
      - RabbitMq__HostName=rabbit
      - RabbitMq__Port=5672
      - RabbitMq__VirtualHost=production
      - RabbitMq__UserName=holidays
      - RabbitMq__Password=payAlot
      - Selenium__RemoteWebDriverUrl=http://selenium-2:4444/wd/hub

  collecting-app-3:
    build:
      context: ./../src/
      dockerfile: ./Holidays.CollectingApp/Dockerfile
    depends_on:
      - postgres
      - selenium-3
      - rabbit
      - collecting-app-2
    environment:
      - ENVIRONMENT=Docker
      - OffersDataSource__Provider=Itaka
      - OffersDataSource__CollectingTimeoutSeconds=60
      - Postgres__ConnectionString=Server=postgres;Port=5432;Database=holidays;User Id=holidays;Password=payAlot;
      - RabbitMq__HostName=rabbit
      - RabbitMq__Port=5672
      - RabbitMq__VirtualHost=production
      - RabbitMq__UserName=holidays
      - RabbitMq__Password=payAlot
      - Selenium__RemoteWebDriverUrl=http://selenium-3:4444/wd/hub

  webapi-app:
    build:
      context: ./../src/
      dockerfile: ./Holidays.WebAPI/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - postgres
      - rabbit
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=5001
      - Postgres__ConnectionString=Server=postgres;Port=5432;Database=holidays;User Id=holidays;Password=payAlot;
      - RabbitMq__HostName=rabbit
      - RabbitMq__Port=5672
      - RabbitMq__VirtualHost=production
      - RabbitMq__UserName=holidays
      - RabbitMq__Password=payAlot

volumes:
  pgdata: { }
