version: "3.9"

services:

  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=holidays
      - POSTGRES_USER=holidays
      - POSTGRES_PASSWORD=payAlot

  pgadmin:
    build:
      context: .
      dockerfile: ./pgadmin/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=changeme
      - PGADMIN_LISTEN_PORT=80

  selenium:
    build:
      context: .
      dockerfile: ./selenium/Dockerfile
    ports:
      - "4444:4444"
    shm_size: '2gb'

volumes:
  pgdata: {}
